### ISSUE TITLE
v0.18 missing attribute 'definition'

### ISSUE THREAD

**Issue by function-store** [AlphaMoonbaseBerlin/TD_Event_Listener_System#1]
`  File "/project/Sources/eventEmitter/EventEmitter", line 83, in Emit
  File "/project/Sources/eventEmitter/EventEmitter", line 54, in check_event
AttributeError: 'EventEmitter' object has no attribute 'definition'`

Checked the code against v0.17 and indeed this attribute is missing

**Comment by function-store** [comment]
`self.definition = self.load_definition()` missing from Init

**Comment by AlphaMoonbaseBerlin** [comment]
Fixed in 0.22
Sorry, took a while.
